version: '3.3'

networks:
  mq-net:
    driver: bridge

services:
  # Kafka
  zookeeper-server:
    image: "bitnami/zookeeper:latest"
    networks:
      - mq-net
    restart: always
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka-server-1:
    image: "bitnami/kafka:latest"
    networks:
      - mq-net
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper-server:2181
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper-server

  # Pulsar
  pulsar-server-1:
    networks:
      - mq-net
    image: "apachepulsar/pulsar:latest"
    ports:
      - "6650:6650"
      - "8080:8080"
    command: >
      /bin/bash -c
      "bin/apply-config-from-env.py conf/standalone.conf
      && bin/pulsar standalone"

  pulsar-dashboard:
    networks:
      - mq-net
    image: apachepulsar/pulsar-dashboard
    depends_on:
      - pulsar-server-1
    ports:
      - "80:80"
    environment:
      - SERVICE_URL=http://localhost:8080

  # RabbitMQ
  rabbitmq-server-1:
    networks:
      - mq-net
    image: "rabbitmq:3-management"
    ports:
      - "15672:15672"
      - "5672:5672"

